### ISSUE TITLE
import by an easy way

### ISSUE THREAD

**Issue by nearchan** [Crossoid/Kotlin-Native-BigDecimal#1]
can I import this project just like implementation("com.xxx.xxx:1.0.0") ?

**Comment by kendy** [comment]
Hello, so far I haven't been providing binary builds, but will have a look how to do that, thanks for the idea!

**Comment by kendy** [comment]
Binary packages are now available, how to use them is visible in an example project: https://github.com/Crossoid/Kotlin-Native-BigDecimal-Example

Hope this helps, please let me know should you have any questions!
